# Generated by Django 3.2.10 on 2022-03-04 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bangazon_api', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_products',
            field=models.ManyToManyField(related_name='products', through='bangazon_api.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
